config/routes.rb
Rails.application.routes.draw do
  resources :categories, :products

  root 'products#index'
  get 'pages/about'
  get 'pages/contact'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, :price, presence: true
  validates :name, confirmation: true
  validates :name_confirmation, presence: true
  validates :price,
    numericality: {
      greater_than: 0,
      less_than: 10000
    }
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end

  def contact
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy], except: [:update_all]

  def index
    # if params[:min].nil? || params[:max].nil?
    #   @products = Product.all
    # else
    #   min, max = params[:min].to_i, params[:max].to_i
    #   @products = Product.where(price: min..max)
    # end
    @products = Product.all
    @products = @products.where('price >= ?', params[:min]) if params[:min].present?
    @products = @products.where('price <= ?', params[:max]) if params[:max].present?

    xsc = (params[:desc].present? ? :desc : :asc)
    @products = @products.order(params[:order] => xsc) if params[:order].present?

    per_page = 10
    page = params[:p].to_i - 1
    offset = page * per_page
    @products = @products.limit(per_page).offset(offset)
    @max_page = Product.count / per_page + 1
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_all
    @p = Product.find(params[:ids])
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name,
                                      :name_confirmation,
                                      :desc,
                                      :price,
                                      :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_li name, url
    is_active = (request.path == url ? 'active' :nil)
    content_tag :li, link_to(name, url), class: is_active
  end
  def page_li page_number
    is_active = (params[:p].to_i == page_number ? 'active' :nil)
    content_tag :li, class: is_active do
      link_to page_number, products_path(p: page_number)
    end
  end
  def price_range range, blank
    number_field_tag range, params[range], class: 'form-control', placeholder: blank
  end
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>
  <br>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1 class="page-header">Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1 class="page-header">Listing categories</h1>
  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr class="info">
          <th>Name</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= category.name %></td>
            <td><%= link_to 'Show', category %></td>
            <td><%= link_to 'Edit', edit_category_path(category) %></td>
            <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1 class="page-header">New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Products:</strong>
  <% @category.products.each do |product| %>
  <li><%= link_to product.name, product %></li>
  <% end %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <%= link_to 'Product', products_path, class: "navbar-brand" %>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav">
    <%= nav_li 'Products', products_path %>
    <%= nav_li 'Categories', categories_path %>
    <%= nav_li 'About', pages_about_path %>
    <%= nav_li 'Contact', pages_contact_path %>
  </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Blank</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
</head>
<body>

  <%= render 'layouts/navbar' %>

  <div class="container">
    <%= yield %>
  </div>

  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

</body>
</html>

app/views/pages/about.html.erb
about
<br>
<br>
<br>
form_for test
<% Product.all.each do |product| %>
  <%= form_for product do |f| %>
    <%= f.text_field :name %>
    <%= f.submit %>
  <% end %>
<% end %>

app/views/pages/contact.html.erb
contact

app/views/products/_form.html.erb
<%= simple_form_for(@product, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :name_confirmation %>
    <%= f.input :desc %>
    <%= f.input :price %>
    <%= f.select :category_id, Category.all.collect { |x| x.name }, { include_blank: "選擇類別" }, :class => "btn btn-default btn-lg" %>
  </div>
  <br>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/products/_search.html.erb
<%= form_tag products_path, method: 'get', class: 'navbar-form navbar-left', role: 'search' do %>
  搜尋價錢範圍：
  <div class="form-group">
    <%= price_range :min, 'min-price' %>
    <%= price_range :max, 'max-price' %>

    <select name="order" class="btn btn-default btn-lg">
      <%= options_for_select [['PRICE', 'price'], ['ID', 'id']], params[:order] %>
    </select>

    <%= check_box_tag :desc, value: true %>由大到小排列
  </div>
  <%= button_tag '搜尋', class: "btn btn-primary" %>
<% end %>

app/views/products/edit.html.erb
<h1 class="page-header">Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1 class="page-header">Listing products</h1>
<%= render 'search' %>
  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr class="info">
          <th>Product ID</th>
          <th>Name</th>
          <th>Desc</th>
          <th>Price</th>
          <th>Category</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @products.each do |product| %>
          <%= content_tag_for :tr, product do %> <!-- product.id動態改變,適用于javascript -->
            <td><%= product.id %></td>
            <td><%= product.name %></td>
            <td><%= product.desc %></td>
            <td><%= product.price %></td>
            <td><%= link_to product.category.try(:name), product.category %></td>
            <td><%= link_to 'Show', product_path(product) %></td>
            <td><%= link_to 'Edit', [:edit, product] %></td>
            <td><%= link_to 'Destroy', product, data: { method: :delete, confirm: 'Are you sure?' } %></td>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
<br>
<ul class="pagination">
  <li><a href="#">&laquo;</a></li>
  <% @max_page.times do |page| %>
    <%= page_li page + 1 %>
  <% end %>
  <li><a href="#">&raquo;</a></li>
</ul>
<br>
<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1 class="page-header">New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @product.desc %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category_id %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>